// src/config/providers.ts
// ========================================
// 拡張可能なプロバイダー設定
// 新しいウォレット・チェーン・取引所・通貨を追加するには、このファイルに1エントリ追加するだけ
// ========================================

// チェーン設定
export const CHAINS = {
    ethereum: {
        key: 'ethereum',
        name: 'Ethereum',
        symbol: 'ETH',
        icon: 'Ξ',
        type: 'evm' as const,
        decimals: 18,
        addressRegex: /^0x[a-fA-F0-9]{40}$/,
        explorer: 'https://etherscan.io',
        rpcUrl: 'https://eth.public-rpc.com',
        enabled: true,
    },
    polygon: {
        key: 'polygon',
        name: 'Polygon',
        symbol: 'MATIC',
        icon: '◆',
        type: 'evm' as const,
        decimals: 18,
        addressRegex: /^0x[a-fA-F0-9]{40}$/,
        explorer: 'https://polygonscan.com',
        rpcUrl: 'https://polygon-rpc.com',
        enabled: true,
    },
    arbitrum: {
        key: 'arbitrum',
        name: 'Arbitrum',
        symbol: 'ETH',
        icon: '🔷',
        type: 'evm' as const,
        decimals: 18,
        addressRegex: /^0x[a-fA-F0-9]{40}$/,
        explorer: 'https://arbiscan.io',
        rpcUrl: 'https://arb1.arbitrum.io/rpc',
        enabled: true,
    },
    optimism: {
        key: 'optimism',
        name: 'Optimism',
        symbol: 'ETH',
        icon: '🔴',
        type: 'evm' as const,
        decimals: 18,
        addressRegex: /^0x[a-fA-F0-9]{40}$/,
        explorer: 'https://optimistic.etherscan.io',
        rpcUrl: 'https://mainnet.optimism.io',
        enabled: true,
    },
    base: {
        key: 'base',
        name: 'Base',
        symbol: 'ETH',
        icon: '🔵',
        type: 'evm' as const,
        decimals: 18,
        addressRegex: /^0x[a-fA-F0-9]{40}$/,
        explorer: 'https://basescan.org',
        rpcUrl: 'https://mainnet.base.org',
        enabled: true,
    },
    bitcoin: {
        key: 'bitcoin',
        name: 'Bitcoin',
        symbol: 'BTC',
        icon: '₿',
        type: 'utxo' as const,
        decimals: 8,
        addressRegex: /^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,90}$/,
        explorer: 'https://blockstream.info',
        rpcUrl: null, // UTXO chains use different API endpoints
        enabled: true,
    },
    solana: {
        key: 'solana',
        name: 'Solana',
        symbol: 'SOL',
        icon: '◎',
        type: 'solana' as const,
        decimals: 9,
        addressRegex: /^[1-9A-HJ-NP-Za-km-z]{32,44}$/,
        explorer: 'https://solscan.io',
        rpcUrl: 'https://api.mainnet-beta.solana.com',
        enabled: true,
    },
    bnb: {
        key: 'bnb',
        name: 'BNB Smart Chain',
        symbol: 'BNB',
        icon: '🟡',
        type: 'evm' as const,
        decimals: 18,
        addressRegex: /^0x[a-fA-F0-9]{40}$/,
        explorer: 'https://bscscan.com',
        rpcUrl: 'https://bsc-dataseed.binance.org',
        enabled: true,
    },
    avalanche: {
        key: 'avalanche',
        name: 'Avalanche',
        symbol: 'AVAX',
        icon: '🔺',
        type: 'evm' as const,
        decimals: 18,
        addressRegex: /^0x[a-fA-F0-9]{40}$/,
        explorer: 'https://snowtrace.io',
        rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
        enabled: true,
    },
} as const;

export type ChainKey = keyof typeof CHAINS;
export type ChainType = 'evm' | 'utxo' | 'solana';

// ウォレットプロバイダー設定 (Top 30 by Market Share)
export const WALLET_PROVIDERS = {
    // Top Tier (Most Popular)
    metamask: {
        key: 'metamask',
        name: 'MetaMask',
        supportedChains: ['ethereum', 'polygon', 'arbitrum', 'optimism', 'base', 'bnb', 'avalanche'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).ethereum?.isMetaMask,
        icon: '/icons/wallets/metamask.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    phantom: {
        key: 'phantom',
        name: 'Phantom',
        supportedChains: ['solana', 'ethereum', 'polygon', 'bitcoin'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).phantom,
        icon: '/icons/wallets/phantom.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    walletconnect: {
        key: 'walletconnect',
        name: 'WalletConnect',
        supportedChains: ['ethereum', 'polygon', 'arbitrum', 'optimism', 'base', 'bnb', 'avalanche'] as ChainKey[],
        detection: () => true, // Always available (QR code)
        icon: '/icons/wallets/walletconnect.svg',
        type: 'qr_code' as const,
        enabled: true,
    },
    coinbase: {
        key: 'coinbase',
        name: 'Coinbase Wallet',
        supportedChains: ['ethereum', 'polygon', 'arbitrum', 'optimism', 'base'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).coinbaseWalletExtension,
        icon: '/icons/wallets/coinbase.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    trust: {
        key: 'trust',
        name: 'Trust Wallet',
        supportedChains: ['ethereum', 'bnb', 'polygon'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).trustwallet,
        icon: '/icons/wallets/trust.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },

    // High Tier
    okx: {
        key: 'okx',
        name: 'OKX Wallet',
        supportedChains: ['ethereum', 'polygon', 'arbitrum', 'optimism', 'bnb'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).okxwallet,
        icon: '/icons/wallets/okx.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    rabby: {
        key: 'rabby',
        name: 'Rabby Wallet',
        supportedChains: ['ethereum', 'polygon', 'arbitrum', 'optimism', 'base', 'bnb', 'avalanche'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).rabby,
        icon: '/icons/wallets/rabby.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    brave: {
        key: 'brave',
        name: 'Brave Wallet',
        supportedChains: ['ethereum', 'polygon', 'arbitrum', 'optimism', 'solana'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).ethereum?.isBraveWallet,
        icon: '/icons/wallets/brave.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    zerion: {
        key: 'zerion',
        name: 'Zerion Wallet',
        supportedChains: ['ethereum', 'polygon', 'arbitrum', 'optimism', 'base'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).zerionWallet,
        icon: '/icons/wallets/zerion.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    rainbow: {
        key: 'rainbow',
        name: 'Rainbow Wallet',
        supportedChains: ['ethereum', 'polygon', 'arbitrum', 'optimism', 'base'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).rainbow,
        icon: '/icons/wallets/rainbow.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },

    // Mid Tier
    exodus: {
        key: 'exodus',
        name: 'Exodus Wallet',
        supportedChains: ['ethereum', 'polygon', 'bnb', 'solana', 'bitcoin'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).exodus,
        icon: '/icons/wallets/exodus.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    argent: {
        key: 'argent',
        name: 'Argent Wallet',
        supportedChains: ['ethereum'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).argentX,
        icon: '/icons/wallets/argent.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    mathwallet: {
        key: 'mathwallet',
        name: 'Math Wallet',
        supportedChains: ['ethereum', 'bnb', 'polygon'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).ethereum?.isMathWallet,
        icon: '/icons/wallets/mathwallet.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    bitget: {
        key: 'bitgetwallet',
        name: 'Bitget Wallet',
        supportedChains: ['ethereum', 'bnb', 'polygon'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).bitkeep,
        icon: '/icons/wallets/bitget.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    tokenpocket: {
        key: 'tokenpocket',
        name: 'TokenPocket',
        supportedChains: ['ethereum', 'bnb', 'polygon'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).ethereum?.isTokenPocket,
        icon: '/icons/wallets/tokenpocket.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    safepal: {
        key: 'safepal',
        name: 'SafePal',
        supportedChains: ['ethereum', 'bnb', 'polygon'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).safepal,
        icon: '/icons/wallets/safepal.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    oneinch: {
        key: 'oneinch',
        name: '1inch Wallet',
        supportedChains: ['ethereum', 'polygon', 'bnb'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).oneinchWallet,
        icon: '/icons/wallets/1inch.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },

    // Solana Ecosystem
    solflare: {
        key: 'solflare',
        name: 'Solflare',
        supportedChains: ['solana'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).solflare,
        icon: '/icons/wallets/solflare.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    backpack: {
        key: 'backpack',
        name: 'Backpack',
        supportedChains: ['solana'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).backpack,
        icon: '/icons/wallets/backpack.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },

    // Bitcoin Wallets
    unisat: {
        key: 'unisat',
        name: 'UniSat',
        supportedChains: ['bitcoin'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).unisat,
        icon: '/icons/wallets/unisat.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    xverse: {
        key: 'xverse',
        name: 'Xverse',
        supportedChains: ['bitcoin'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).XverseProviders,
        icon: '/icons/wallets/xverse.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },

    // Additional Popular Wallets
    ledgerlive: {
        key: 'ledgerlive',
        name: 'Ledger Live',
        supportedChains: ['ethereum', 'bitcoin', 'polygon'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).ethereum?.isLedgerConnect,
        icon: '/icons/wallets/ledger.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    gate: {
        key: 'gatewallet',
        name: 'Gate Wallet',
        supportedChains: ['ethereum', 'bnb', 'polygon'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).gatewallet,
        icon: '/icons/wallets/gate.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    bybit: {
        key: 'bybitwallet',
        name: 'Bybit Wallet',
        supportedChains: ['ethereum', 'bnb'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).bybitWallet,
        icon: '/icons/wallets/bybit.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    binance: {
        key: 'binancewallet',
        name: 'Binance Wallet',
        supportedChains: ['ethereum', 'bnb'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).BinanceChain,
        icon: '/icons/wallets/binance.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    cryptocom: {
        key: 'cryptocomwallet',
        name: 'Crypto.com DeFi Wallet',
        supportedChains: ['ethereum', 'polygon'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).deficonnectProvider,
        icon: '/icons/wallets/cryptocom.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    enkrypt: {
        key: 'enkrypt',
        name: 'Enkrypt Wallet',
        supportedChains: ['ethereum', 'polygon', 'bnb'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).enkrypt,
        icon: '/icons/wallets/enkrypt.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
    frame: {
        key: 'frame',
        name: 'Frame Wallet',
        supportedChains: ['ethereum'] as ChainKey[],
        detection: () => typeof window !== 'undefined' && !!(window as any).ethereum?.isFrame,
        icon: '/icons/wallets/frame.svg',
        type: 'browser_extension' as const,
        enabled: true,
    },
} as const;

export type WalletProviderKey = keyof typeof WALLET_PROVIDERS;

// 取引所設定 (Top 50 by Trading Volume)
export const EXCHANGES = {
    // Tier 1 - Top 10 Volume
    binance: {
        key: 'binance',
        name: 'Binance',
        slug: 'binance',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/binance.svg',
        enabled: true,
        websiteUrl: 'https://www.binance.com',
        apiDocsUrl: 'https://binance-docs.github.io/apidocs/',
    },
    coinbase: {
        key: 'coinbase',
        name: 'Coinbase Exchange',
        slug: 'coinbase',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/coinbase.svg',
        enabled: true,
        websiteUrl: 'https://www.coinbase.com',
        apiDocsUrl: 'https://docs.cloud.coinbase.com/',
    },
    okx: {
        key: 'okx',
        name: 'OKX',
        slug: 'okx',
        fields: ['apiKey', 'apiSecret', 'passphrase'] as const,
        icon: '/icons/exchanges/okx.svg',
        enabled: true,
        websiteUrl: 'https://www.okx.com',
        apiDocsUrl: 'https://www.okx.com/docs-v5/en/',
    },
    bybit: {
        key: 'bybit',
        name: 'Bybit',
        slug: 'bybit',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bybit.svg',
        enabled: true,
        websiteUrl: 'https://www.bybit.com',
        apiDocsUrl: 'https://bybit-exchange.github.io/docs/',
    },
    bitget: {
        key: 'bitget',
        name: 'Bitget',
        slug: 'bitget',
        fields: ['apiKey', 'apiSecret', 'passphrase'] as const,
        icon: '/icons/exchanges/bitget.svg',
        enabled: true,
        websiteUrl: 'https://www.bitget.com',
        apiDocsUrl: 'https://bitgetlimited.github.io/apidoc/en/mix/',
    },
    gateio: {
        key: 'gateio',
        name: 'Gate.io',
        slug: 'gate',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/gateio.svg',
        enabled: true,
        websiteUrl: 'https://www.gate.io',
        apiDocsUrl: 'https://www.gate.io/docs/developers/apiv4/',
    },
    kucoin: {
        key: 'kucoin',
        name: 'KuCoin',
        slug: 'kucoin',
        fields: ['apiKey', 'apiSecret', 'passphrase'] as const,
        icon: '/icons/exchanges/kucoin.svg',
        enabled: true,
        websiteUrl: 'https://www.kucoin.com',
        apiDocsUrl: 'https://docs.kucoin.com/',
    },
    kraken: {
        key: 'kraken',
        name: 'Kraken',
        slug: 'kraken',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/kraken.svg',
        enabled: true,
        websiteUrl: 'https://www.kraken.com',
        apiDocsUrl: 'https://docs.kraken.com/rest/',
    },
    htx: {
        key: 'htx',
        name: 'HTX (Huobi)',
        slug: 'htx',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/htx.svg',
        enabled: true,
        websiteUrl: 'https://www.htx.com',
        apiDocsUrl: 'https://www.htx.com/en-us/opend/newApiPages/',
    },
    cryptocom: {
        key: 'cryptocom',
        name: 'Crypto.com Exchange',
        slug: 'crypto_com',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/cryptocom.svg',
        enabled: true,
        websiteUrl: 'https://crypto.com',
        apiDocsUrl: 'https://exchange-docs.crypto.com/exchange/v1/rest-ws/index.html',
    },

    // Tier 2 - Top 11-30
    bitfinex: {
        key: 'bitfinex',
        name: 'Bitfinex',
        slug: 'bitfinex',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bitfinex.svg',
        enabled: true,
        websiteUrl: 'https://www.bitfinex.com',
        apiDocsUrl: 'https://docs.bitfinex.com/docs',
    },
    bingx: {
        key: 'bingx',
        name: 'BingX',
        slug: 'bingx',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bingx.svg',
        enabled: true,
        websiteUrl: 'https://bingx.com',
        apiDocsUrl: 'https://bingx-api.github.io/docs/',
    },
    mexc: {
        key: 'mexc',
        name: 'MEXC',
        slug: 'mexc',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/mexc.svg',
        enabled: true,
        websiteUrl: 'https://www.mexc.com',
        apiDocsUrl: 'https://mxcdevelop.github.io/apidocs/',
    },
    bitmart: {
        key: 'bitmart',
        name: 'BitMart',
        slug: 'bitmart',
        fields: ['apiKey', 'apiSecret', 'memo'] as const,
        icon: '/icons/exchanges/bitmart.svg',
        enabled: true,
        websiteUrl: 'https://www.bitmart.com',
        apiDocsUrl: 'https://developer-pro.bitmart.com/',
    },
    lbank: {
        key: 'lbank',
        name: 'LBank',
        slug: 'lbank',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/lbank.svg',
        enabled: true,
        websiteUrl: 'https://www.lbank.com',
        apiDocsUrl: 'https://www.lbank.com/en-US/docs/index.html',
    },
    bitflyer: {
        key: 'bitflyer',
        name: 'bitFlyer',
        slug: 'bitflyer',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bitflyer.svg',
        enabled: true,
        websiteUrl: 'https://bitflyer.com',
        apiDocsUrl: 'https://lightning.bitflyer.com/docs',
    },
    gemini: {
        key: 'gemini',
        name: 'Gemini',
        slug: 'gemini',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/gemini.svg',
        enabled: true,
        websiteUrl: 'https://www.gemini.com',
        apiDocsUrl: 'https://docs.gemini.com/rest-api/',
    },
    bitstamp: {
        key: 'bitstamp',
        name: 'Bitstamp',
        slug: 'bitstamp',
        fields: ['apiKey', 'apiSecret', 'customerId'] as const,
        icon: '/icons/exchanges/bitstamp.svg',
        enabled: true,
        websiteUrl: 'https://www.bitstamp.net',
        apiDocsUrl: 'https://www.bitstamp.net/api/',
    },
    upbit: {
        key: 'upbit',
        name: 'Upbit',
        slug: 'upbit',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/upbit.svg',
        enabled: true,
        websiteUrl: 'https://upbit.com',
        apiDocsUrl: 'https://docs.upbit.com/docs',
    },
    bithumb: {
        key: 'bithumb',
        name: 'Bithumb',
        slug: 'bithumb',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bithumb.svg',
        enabled: true,
        websiteUrl: 'https://www.bithumb.com',
        apiDocsUrl: 'https://apidocs.bithumb.com/',
    },

    // Tier 3 - Top 31-50
    coincheck: {
        key: 'coincheck',
        name: 'Coincheck',
        slug: 'coincheck',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/coincheck.svg',
        enabled: true,
        websiteUrl: 'https://coincheck.com',
        apiDocsUrl: 'https://coincheck.com/documents/exchange/api',
    },
    poloniex: {
        key: 'poloniex',
        name: 'Poloniex',
        slug: 'poloniex',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/poloniex.svg',
        enabled: true,
        websiteUrl: 'https://poloniex.com',
        apiDocsUrl: 'https://docs.poloniex.com/',
    },
    whitebit: {
        key: 'whitebit',
        name: 'WhiteBIT',
        slug: 'whitebit',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/whitebit.svg',
        enabled: true,
        websiteUrl: 'https://whitebit.com',
        apiDocsUrl: 'https://docs.whitebit.com/',
    },
    bitso: {
        key: 'bitso',
        name: 'Bitso',
        slug: 'bitso',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bitso.svg',
        enabled: true,
        websiteUrl: 'https://bitso.com',
        apiDocsUrl: 'https://bitso.com/api_info/',
    },
    phemex: {
        key: 'phemex',
        name: 'Phemex',
        slug: 'phemex',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/phemex.svg',
        enabled: true,
        websiteUrl: 'https://phemex.com',
        apiDocsUrl: 'https://github.com/phemex/phemex-api-docs',
    },
    coinex: {
        key: 'coinex',
        name: 'CoinEx',
        slug: 'coinex',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/coinex.svg',
        enabled: true,
        websiteUrl: 'https://www.coinex.com',
        apiDocsUrl: 'https://docs.coinex.com/',
    },
    ascendex: {
        key: 'ascendex',
        name: 'AscendEX',
        slug: 'ascendex',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/ascendex.svg',
        enabled: true,
        websiteUrl: 'https://ascendex.com',
        apiDocsUrl: 'https://ascendex.github.io/ascendex-pro-api/',
    },
    bitkub: {
        key: 'bitkub',
        name: 'Bitkub',
        slug: 'bitkub',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bitkub.svg',
        enabled: true,
        websiteUrl: 'https://www.bitkub.com',
        apiDocsUrl: 'https://github.com/bitkub/bitkub-official-api-docs',
    },
    bitbank: {
        key: 'bitbank',
        name: 'bitbank',
        slug: 'bitbank',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bitbank.svg',
        enabled: true,
        websiteUrl: 'https://bitbank.cc',
        apiDocsUrl: 'https://github.com/bitbankinc/bitbank-api-docs',
    },
    btcturk: {
        key: 'btcturk',
        name: 'BtcTurk',
        slug: 'btcturk',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/btcturk.svg',
        enabled: true,
        websiteUrl: 'https://www.btcturk.com',
        apiDocsUrl: 'https://docs.btcturk.com/',
    },
    indodax: {
        key: 'indodax',
        name: 'Indodax',
        slug: 'indodax',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/indodax.svg',
        enabled: true,
        websiteUrl: 'https://indodax.com',
        apiDocsUrl: 'https://github.com/btcid/indodax-official-api-docs',
    },
    cexio: {
        key: 'cexio',
        name: 'CEX.IO',
        slug: 'cexio',
        fields: ['apiKey', 'apiSecret', 'userId'] as const,
        icon: '/icons/exchanges/cexio.svg',
        enabled: true,
        websiteUrl: 'https://cex.io',
        apiDocsUrl: 'https://docs.cex.io/',
    },
    bitrue: {
        key: 'bitrue',
        name: 'Bitrue',
        slug: 'bitrue',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/bitrue.svg',
        enabled: true,
        websiteUrl: 'https://www.bitrue.com',
        apiDocsUrl: 'https://github.com/Bitrue-exchange/bitrue-official-api-docs',
    },
    exmo: {
        key: 'exmo',
        name: 'EXMO',
        slug: 'exmo',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/exmo.svg',
        enabled: true,
        websiteUrl: 'https://exmo.com',
        apiDocsUrl: 'https://documenter.getpostman.com/view/10287440/SzYXWKPi',
    },
    digifinex: {
        key: 'digifinex',
        name: 'DigiFinex',
        slug: 'digifinex',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/digifinex.svg',
        enabled: true,
        websiteUrl: 'https://www.digifinex.com',
        apiDocsUrl: 'https://docs.digifinex.com/',
    },
    probit: {
        key: 'probit',
        name: 'ProBit Global',
        slug: 'probit',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/probit.svg',
        enabled: true,
        websiteUrl: 'https://www.probit.com',
        apiDocsUrl: 'https://docs-en.probit.com/docs',
    },
    zaif: {
        key: 'zaif',
        name: 'Zaif',
        slug: 'zaif',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/zaif.svg',
        enabled: true,
        websiteUrl: 'https://zaif.jp',
        apiDocsUrl: 'https://zaif-api-document.readthedocs.io/',
    },
    latoken: {
        key: 'latoken',
        name: 'LATOKEN',
        slug: 'latoken',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/latoken.svg',
        enabled: true,
        websiteUrl: 'https://latoken.com',
        apiDocsUrl: 'https://api.latoken.com/',
    },
    btse: {
        key: 'btse',
        name: 'BTSE',
        slug: 'btse',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/btse.svg',
        enabled: true,
        websiteUrl: 'https://www.btse.com',
        apiDocsUrl: 'https://www.btse.com/apiexplorer/spot/',
    },
    luno: {
        key: 'luno',
        name: 'Luno',
        slug: 'luno',
        fields: ['apiKey', 'apiSecret'] as const,
        icon: '/icons/exchanges/luno.svg',
        enabled: true,
        websiteUrl: 'https://www.luno.com',
        apiDocsUrl: 'https://www.luno.com/en/developers/api',
    },
} as const;

export type ExchangeKey = keyof typeof EXCHANGES;

// 通貨設定
export const CURRENCIES = {
    // メジャー暗号通貨
    BTC: { code: 'BTC', name: 'Bitcoin', decimals: 8, type: 'crypto' as const, icon: '₿' },
    ETH: { code: 'ETH', name: 'Ethereum', decimals: 18, type: 'crypto' as const, icon: 'Ξ' },
    SOL: { code: 'SOL', name: 'Solana', decimals: 9, type: 'crypto' as const, icon: '◎' },
    BNB: { code: 'BNB', name: 'BNB', decimals: 18, type: 'crypto' as const, icon: '🟡' },
    AVAX: { code: 'AVAX', name: 'Avalanche', decimals: 18, type: 'crypto' as const, icon: '🔺' },
    MATIC: { code: 'MATIC', name: 'Polygon', decimals: 18, type: 'crypto' as const, icon: '◆' },

    // ステーブルコイン
    USDT: { code: 'USDT', name: 'Tether', decimals: 6, type: 'stablecoin' as const, icon: '₮' },
    USDC: { code: 'USDC', name: 'USD Coin', decimals: 6, type: 'stablecoin' as const, icon: '⊙' },
    DAI: { code: 'DAI', name: 'Dai', decimals: 18, type: 'stablecoin' as const, icon: '◈' },
    BUSD: { code: 'BUSD', name: 'Binance USD', decimals: 18, type: 'stablecoin' as const, icon: '💲' },

    // アルトコイン
    XRP: { code: 'XRP', name: 'Ripple', decimals: 6, type: 'crypto' as const, icon: '⊗' },
    ADA: { code: 'ADA', name: 'Cardano', decimals: 6, type: 'crypto' as const, icon: '₳' },
    DOGE: { code: 'DOGE', name: 'Dogecoin', decimals: 8, type: 'crypto' as const, icon: 'Ð' },
    DOT: { code: 'DOT', name: 'Polkadot', decimals: 10, type: 'crypto' as const, icon: '●' },
    LINK: { code: 'LINK', name: 'Chainlink', decimals: 18, type: 'crypto' as const, icon: '🔗' },
    UNI: { code: 'UNI', name: 'Uniswap', decimals: 18, type: 'crypto' as const, icon: '🦄' },
    AAVE: { code: 'AAVE', name: 'Aave', decimals: 18, type: 'crypto' as const, icon: '👻' },

    // 法定通貨
    USD: { code: 'USD', name: 'US Dollar', decimals: 2, type: 'fiat' as const, icon: '$' },
    JPY: { code: 'JPY', name: 'Japanese Yen', decimals: 0, type: 'fiat' as const, icon: '¥' },
    EUR: { code: 'EUR', name: 'Euro', decimals: 2, type: 'fiat' as const, icon: '€' },
    GBP: { code: 'GBP', name: 'British Pound', decimals: 2, type: 'fiat' as const, icon: '£' },
    KRW: { code: 'KRW', name: 'Korean Won', decimals: 0, type: 'fiat' as const, icon: '₩' },
} as const;

export type CurrencyCode = keyof typeof CURRENCIES;
export type CurrencyType = 'crypto' | 'stablecoin' | 'fiat';

// ヘルパー関数
export const getEnabledChains = () =>
    Object.values(CHAINS).filter(chain => chain.enabled);

export const getEnabledWallets = () =>
    Object.values(WALLET_PROVIDERS).filter(wallet => wallet.enabled);

export const getEnabledExchanges = () =>
    Object.values(EXCHANGES).filter(exchange => exchange.enabled);

export const detectChainByAddress = (address: string) => {
    for (const chain of Object.values(CHAINS)) {
        if (chain.addressRegex.test(address)) {
            return chain;
        }
    }
    return null;
};

export const getWalletsByChain = (chainKey: ChainKey) =>
    Object.values(WALLET_PROVIDERS).filter(wallet =>
        wallet.enabled && wallet.supportedChains.includes(chainKey)
    );

export const getCurrenciesByType = (type: CurrencyType) =>
    Object.values(CURRENCIES).filter(currency => currency.type === type);
