-- Ensure transaction_usage_labels exists to prevent view breakage
-- and enable RLS for security.

CREATE TABLE IF NOT EXISTS public.transaction_usage_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    tx_id BIGINT, -- Logical FK to wallet_transactions.id
    ctx_id TEXT,  -- Logical FK to exchange_trades.trade_id
    usage_key TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.transaction_usage_labels ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='transaction_usage_labels' AND policyname='auth_select_usage_labels'
  ) THEN
    CREATE POLICY auth_select_usage_labels
      ON public.transaction_usage_labels FOR SELECT
      TO authenticated
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='transaction_usage_labels' AND policyname='auth_insert_usage_labels'
  ) THEN
    CREATE POLICY auth_insert_usage_labels
      ON public.transaction_usage_labels FOR INSERT
      TO authenticated
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='transaction_usage_labels' AND policyname='auth_update_usage_labels'
  ) THEN
    CREATE POLICY auth_update_usage_labels
      ON public.transaction_usage_labels FOR UPDATE
      TO authenticated
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
  
   IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='transaction_usage_labels' AND policyname='auth_delete_usage_labels'
  ) THEN
    CREATE POLICY auth_delete_usage_labels
      ON public.transaction_usage_labels FOR DELETE
      TO authenticated
      USING (auth.uid() = user_id);
  END IF;
END $$;
