// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymddtgbsybvxfitgupqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZGR0Z2JzeWJ2eGZpdGd1cHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjc0MjcsImV4cCI6MjA3MzYwMzQyN30.chcgcQ3Uwpow7PluU-5uvioe1IWIYjCC0QSzdF-T3_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});